//! Per-store data-plane Docker Compose generation — the magento-vm-provisioner
//! fragment pattern (MariaDB, OpenSearch, Redis, Mailpit in containers;
//! nginx + PHP-FPM stay native). Ports bind to 127.0.0.1 only.

/// Default container image refs (full `family:tag`, so overrides can bump a
/// version *or* swap engines, e.g. `mariadb:11.4` or `mysql:8.4`).
pub fn default_service_versions() -> serde_json::Value {
    service_versions_for("default")
}

pub fn service_versions_for(magento_version: &str) -> serde_json::Value {
    if magento_version == "2.4.8-p5" {
        return serde_json::json!({
            "db": "mariadb:11.8",
            "opensearch": "opensearchproject/opensearch:3",
            "redis": "valkey/valkey:8.1-alpine",
            "rabbitmq": "rabbitmq:4.2-management-alpine",
            "varnish": "varnish:8",
            "mailpit": "axllent/mailpit:latest"
        });
    }
    serde_json::json!({
        "db": "mariadb:10.6",
        "opensearch": "opensearchproject/opensearch:2.12.0",
        "redis": "redis:7.2-alpine",
        "rabbitmq": "rabbitmq:3.13-management-alpine",
        "varnish": "varnish:7.4",
        "mailpit": "axllent/mailpit:latest"
    })
}

/// Compose file for one store. `base` is the store's 10-port window.
/// `versions` is the resolved image map (defaults + overrides).
pub fn compose_yaml(
    name: &str,
    base: u16,
    db_password: &str,
    rabbitmq: bool,
    varnish: bool,
    versions: &serde_json::Value,
) -> String {
    let img = |k: &str, d: &str| -> String {
        versions
            .get(k)
            .and_then(|v| v.as_str())
            .filter(|s| !s.is_empty())
            .unwrap_or(d)
            .to_string()
    };
    let db_img = img("db", "mariadb:10.6");
    let search_img = img("opensearch", "opensearchproject/opensearch:2.12.0");
    let redis_img = img("redis", "redis:7.2-alpine");
    let rabbitmq_img = img("rabbitmq", "rabbitmq:3.13-management-alpine");
    let varnish_img = img("varnish", "varnish:7.4");
    let mailpit_img = img("mailpit", "axllent/mailpit:latest");
    let db = base;
    let search = base + 1;
    let redis = base + 2;
    let amqp = base + 3;
    let smtp = base + 4;
    let mail_ui = base + 5;
    let varnish_port = base + 6;
    let varnish_block = if varnish {
        format!(
            r#"
  varnish:
    image: {varnish_img}
    container_name: magento-{name}-varnish
    restart: unless-stopped
    # VCL is bootstrap at first (dumb proxy); provisioning regenerates it
    # with `bin/magento varnish:vcl:generate` after install and restarts.
    volumes:
      - ./default.vcl:/etc/varnish/default.vcl:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: ["varnishd", "-F", "-f", "/etc/varnish/default.vcl", "-a", "http=:80,HTTP", "-s", "malloc,256m"]
    ports:
      - "127.0.0.1:{varnish_port}:80"
"#
        )
    } else {
        String::new()
    };
    let rabbitmq_block = if rabbitmq {
        format!(
            r#"
  rabbitmq:
    image: {rabbitmq_img}
    container_name: magento-{name}-rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: magento
      RABBITMQ_DEFAULT_PASS: "{db_password}"
    ports:
      - "127.0.0.1:{amqp}:5672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 10s
      retries: 20
"#
        )
    } else {
        String::new()
    };
    format!(
        r#"# Generated by ServerKit-rs sk-magento — data plane for store '{name}'
name: magento-{name}

services:
  db:
    image: {db_img}
    container_name: magento-{name}-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: "{db_password}"
      MARIADB_DATABASE: magento
      MARIADB_USER: magento
      MARIADB_PASSWORD: "{db_password}"
    command: --max-allowed-packet=64M --innodb-buffer-pool-size=512M
    ports:
      - "127.0.0.1:{db}:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 30

  opensearch:
    image: {search_img}
    container_name: magento-{name}-opensearch
    restart: unless-stopped
    environment:
      discovery.type: single-node
      DISABLE_SECURITY_PLUGIN: "true"
      DISABLE_INSTALL_DEMO_CONFIG: "true"
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
      bootstrap.memory_lock: "true"
      # Dev-friendly: full host disks otherwise trip the flood-stage
      # watermark, which sets a *persistent* cluster.blocks.create_index
      # that breaks catalogsearch reindexing. Tune for production.
      cluster.routing.allocation.disk.threshold_enabled: "false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "127.0.0.1:{search}:9200"
    volumes:
      - search-data:/usr/share/opensearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:9200/_cluster/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 60

  redis:
    image: {redis_img}
    container_name: magento-{name}-redis
    restart: unless-stopped
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    ports:
      - "127.0.0.1:{redis}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20

  mailpit:
    image: {mailpit_img}
    container_name: magento-{name}-mailpit
    restart: unless-stopped
    ports:
      - "127.0.0.1:{smtp}:1025"
      - "127.0.0.1:{mail_ui}:8025"
{rabbitmq_block}{varnish_block}
volumes:
  db-data:
  search-data:
"#
    )
}

/// nginx upstream names are global — two stores both declaring
/// `fastcgi_backend` (the name nginx.conf.sample hardcodes) collide. Each
/// store gets a unique upstream and a per-store copy of the sample with the
/// reference rewritten (`nginx.conf.serverkit`), which also lets stores run
/// different PHP versions side by side.
pub fn upstream_name(name: &str) -> String {
    format!("fastcgi_backend_{}", name.replace('-', "_"))
}

/// Canonical Magento 2 nginx vhost: delegate to the store's rewritten copy
/// of Magento's nginx.conf.sample with `$MAGE_ROOT` set.
pub fn magento_vhost(name: &str, domain: &str, mage_root: &str, php_version: &str) -> String {
    let upstream = upstream_name(name);
    let pool = name.replace('-', "_");
    format!(
        r#"upstream {upstream} {{
    server unix:/run/php/php{php_version}-fpm-{pool}.sock;
}}

server {{
    listen 80;
    listen [::]:80;
    server_name {domain};

    set $MAGE_ROOT {mage_root};

    access_log /var/log/nginx/{name}.access.log;
    error_log /var/log/nginx/{name}.error.log;

    include {mage_root}/nginx.conf.serverkit;
}}
"#
    )
}

/// Bootstrap VCL: a dumb pass-through proxy to the nginx backend so the
/// varnish container can start before Magento exists. Replaced post-install
/// by the canonical `varnish:vcl:generate` output.
pub fn bootstrap_vcl(backend_port: u16) -> String {
    format!(
        r#"vcl 4.1;

backend default {{
    .host = "host.docker.internal";
    .port = "{backend_port}";
}}
"#
    )
}

/// Varnish-mode vhost — the magento-vm-provisioner proxy architecture:
/// nginx proxy (:80/:443) → varnish container → nginx backend. The backend
/// listens on the docker0 gateway address only, so containers can reach it
/// but the outside world cannot bypass the cache.
pub fn magento_vhost_varnish(
    name: &str,
    domain: &str,
    mage_root: &str,
    php_version: &str,
    varnish_port: u16,
    backend_port: u16,
    ssl: Option<(&str, &str)>,
) -> String {
    let upstream = upstream_name(name);
    let pool = name.replace('-', "_");
    let proxy_block = match ssl {
        Some((cert, key)) => format!(
            r#"server {{
    listen 80;
    listen [::]:80;
    server_name {domain};
    return 301 https://$server_name$request_uri;
}}

server {{
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name {domain};

    ssl_certificate {cert};
    ssl_certificate_key {key};
    ssl_protocols TLSv1.2 TLSv1.3;

    access_log /var/log/nginx/{name}.access.log;

    location / {{
        proxy_pass http://127.0.0.1:{varnish_port};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Ssl-Offloaded "1";
        proxy_read_timeout 300;
        # Magento emits very large X-Magento-Tags headers through varnish
        proxy_buffer_size 32k;
        proxy_buffers 8 32k;
        proxy_busy_buffers_size 64k;
    }}
}}"#
        ),
        None => format!(
            r#"server {{
    listen 80;
    listen [::]:80;
    server_name {domain};

    access_log /var/log/nginx/{name}.access.log;

    location / {{
        proxy_pass http://127.0.0.1:{varnish_port};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 300;
        # Magento emits very large X-Magento-Tags headers through varnish
        proxy_buffer_size 32k;
        proxy_buffers 8 32k;
        proxy_busy_buffers_size 64k;
    }}
}}"#
        ),
    };

    format!(
        r#"upstream {upstream} {{
    server unix:/run/php/php{php_version}-fpm-{pool}.sock;
}}

{proxy_block}

# Cache backend — only reachable from containers via the docker0 gateway.
server {{
    listen 172.17.0.1:{backend_port};
    server_name {domain};

    set $MAGE_ROOT {mage_root};

    access_log /var/log/nginx/{name}.backend.log;
    error_log /var/log/nginx/{name}.error.log;

    include {mage_root}/nginx.conf.serverkit;
}}
"#
    )
}

/// Frontend serving block body: proxy to a Node app (Next/Nuxt dev/SSR) or
/// static files from a built export folder with SPA fallback.
fn frontend_location(frontend_port: i64, frontend_root: Option<&str>) -> String {
    match frontend_root {
        // static mode: port 0 + folder → nginx serves the build output
        Some(root) if frontend_port == 0 => format!(
            r#"    root {root};
    index index.html;

    location / {{
        try_files $uri $uri/ /index.html;
    }}"#
        ),
        _ => format!(
            r#"    location / {{
        proxy_pass http://127.0.0.1:{frontend_port};
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_cache_bypass $http_upgrade;
        proxy_read_timeout 86400;
    }}"#
        ),
    }
}

/// Listen directives + optional ssl config lines for a public server block,
/// plus the HTTP→HTTPS redirect server when ssl is on.
fn public_listen(domain: &str, ssl: Option<(&str, &str)>) -> (String, String) {
    match ssl {
        Some((cert, key)) => (
            format!(
                "    listen 443 ssl http2;\n    listen [::]:443 ssl http2;\n\n    ssl_certificate {cert};\n    ssl_certificate_key {key};\n    ssl_protocols TLSv1.2 TLSv1.3;\n    ssl_session_cache shared:SSL:10m;"
            ),
            format!(
                "server {{\n    listen 80;\n    listen [::]:80;\n    server_name {domain};\n    return 301 https://$server_name$request_uri;\n}}\n\n"
            ),
        ),
        None => ("    listen 80;\n    listen [::]:80;".to_string(), String::new()),
    }
}

fn magento_proxy_location(matcher: &str, backend_port: u16) -> String {
    format!(
        r#"    location {matcher} {{
        proxy_pass http://127.0.0.1:{backend_port};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_buffer_size 32k;
        proxy_buffers 8 32k;
        proxy_busy_buffers_size 64k;
        proxy_read_timeout 300;
    }}"#
    )
}

/// Shared-domain headless vhost (provisioner "shared" mode): ONE domain —
/// the headless frontend serves `/`, while the Magento surfaces (admin path,
/// /rest, /graphql, /static, /media + custom routes) proxy to an internal
/// Magento server block on 127.0.0.1:{backend_port}.
#[allow(clippy::too_many_arguments)]
pub fn magento_vhost_headless_shared(
    name: &str,
    domain: &str,
    mage_root: &str,
    php_version: &str,
    backend_port: u16,
    admin_path: &str,
    frontend_port: i64,
    frontend_root: Option<&str>,
    custom_routes: &[String],
    ssl: Option<(&str, &str)>,
) -> String {
    let upstream = upstream_name(name);
    let pool = name.replace('-', "_");
    let frontend = frontend_location(frontend_port, frontend_root);
    let (listen, redirect) = public_listen(domain, ssl);

    // default Magento surfaces + the store's generated admin path
    let admin = admin_path.trim_start_matches('/').trim_end_matches('/');
    let mut magento_locations = vec![magento_proxy_location(
        &format!("~* ^/({admin}|rest|graphql|static|media|setup)(/|$)"),
        backend_port,
    )];
    // custom path prefixes (validated upstream: must start with /)
    for route in custom_routes {
        magento_locations.push(magento_proxy_location(&format!("^~ {route}"), backend_port));
    }
    let magento_locations = magento_locations.join("\n\n");

    format!(
        r#"upstream {upstream} {{
    server unix:/run/php/php{php_version}-fpm-{pool}.sock;
}}

# Internal Magento backend (headless shared mode) — loopback only
server {{
    listen 127.0.0.1:{backend_port};
    server_name {domain};

    set $MAGE_ROOT {mage_root};

    access_log /var/log/nginx/{name}.backend.log;
    error_log /var/log/nginx/{name}.error.log;

    include {mage_root}/nginx.conf.serverkit;
}}

{redirect}# Headless frontend + routed Magento surfaces
server {{
{listen}
    server_name {domain};

    access_log /var/log/nginx/{name}.access.log;

{magento_locations}

{frontend}
}}
"#
    )
}

/// Three-domain split mode: frontend_domain (FE) + api domain (allowlisted
/// /rest,/graphql,/static,/media only) + admin_domain (admin path + assets,
/// / redirects to the admin path). Both proxy the internal loopback backend.
#[allow(clippy::too_many_arguments)]
pub fn magento_vhost_headless_split(
    name: &str,
    api_domain: &str,
    admin_domain: &str,
    mage_root: &str,
    php_version: &str,
    backend_port: u16,
    admin_path: &str,
    route_mode: &str,
    ssl: Option<(&str, &str)>,
) -> String {
    let upstream = upstream_name(name);
    let pool = name.replace('-', "_");
    let admin = admin_path.trim_start_matches('/').trim_end_matches('/');
    let (api_locations, api_terminal_location, admin_locations, admin_terminal_location) =
        if route_mode == "full_proxy" {
            (
                [
                    magento_proxy_location("^~ /rest", backend_port),
                    magento_proxy_location("~ ^/(en/graphql|vi/graphql|graphql)", backend_port),
                    magento_proxy_location("~ ^/(media/)", backend_port),
                    magento_proxy_location("/", backend_port),
                ]
                .join("\n\n"),
                String::new(),
                [
                    magento_proxy_location("~ ^/(en/graphql|vi/graphql|graphql)", backend_port),
                    magento_proxy_location("~ ^/(media/)", backend_port),
                    magento_proxy_location("/", backend_port),
                ]
                .join("\n\n"),
                String::new(),
            )
        } else {
            (
            magento_proxy_location("~* ^/(rest|graphql|static|media)(/|$)", backend_port),
            "\n    location / {\n        return 404;\n    }\n".to_string(),
            magento_proxy_location(
                &format!("~* ^/({admin}|static|media|setup)(/|$)"),
                backend_port,
            ),
            format!(
                "\n    location = / {{\n        return 302 /{admin};\n    }}\n\n    location / {{\n        return 404;\n    }}\n"
            ),
        )
        };
    let (api_listen, api_redirect) = public_listen(api_domain, ssl);
    let (admin_listen, admin_redirect) = public_listen(admin_domain, ssl);
    format!(
        r#"upstream {upstream} {{
    server unix:/run/php/php{php_version}-fpm-{pool}.sock;
}}

# Internal Magento backend (headless split mode) — loopback only
server {{
    listen 127.0.0.1:{backend_port};
    server_name {api_domain} {admin_domain};

    set $MAGE_ROOT {mage_root};

    access_log /var/log/nginx/{name}.backend.log;
    error_log /var/log/nginx/{name}.error.log;

    include {mage_root}/nginx.conf.serverkit;
}}

{api_redirect}# API domain — route policy: {route_mode}
server {{
{api_listen}
    server_name {api_domain};

    access_log /var/log/nginx/{name}.api.log;

{api_locations}
{api_terminal_location}
}}

{admin_redirect}# Admin domain — route policy: {route_mode}
server {{
{admin_listen}
    server_name {admin_domain};

    access_log /var/log/nginx/{name}.admin.log;

{admin_locations}
{admin_terminal_location}
}}
"#
    )
}

/// systemd unit for a managed headless frontend (Next/Nuxt/custom Node app).
/// PM2-free: systemd is already the process manager for everything else here.
pub fn frontend_unit(name: &str, frontend_root: &str, cmd: &str, port: i64, user: &str) -> String {
    format!(
        r#"[Unit]
Description=ServerKit headless frontend for Magento store {name}
After=network.target

[Service]
Type=simple
User={user}
WorkingDirectory={frontend_root}
Environment=PORT={port}
Environment=NODE_ENV=production
ExecStart={cmd}
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
"#
    )
}

/// Separate-domains headless mode: the frontend domain proxies the Node app
/// (or serves a static export); the Magento store keeps its own full vhost
/// on the api/admin domain (generated separately).
pub fn frontend_vhost(
    name: &str,
    frontend_domain: &str,
    frontend_port: i64,
    frontend_root: Option<&str>,
    ssl: Option<(&str, &str)>,
) -> String {
    let frontend = frontend_location(frontend_port, frontend_root);
    let (listen, redirect) = public_listen(frontend_domain, ssl);
    format!(
        r#"{redirect}server {{
{listen}
    server_name {frontend_domain};

    access_log /var/log/nginx/{name}.frontend.log;

{frontend}
}}
"#
    )
}

/// SSL variant of the Magento vhost: 443 with the store cert + an HTTP→HTTPS
/// redirect. Same nginx.conf.sample delegation as the plain vhost.
pub fn magento_vhost_ssl(
    name: &str,
    domain: &str,
    mage_root: &str,
    php_version: &str,
    cert: &str,
    key: &str,
) -> String {
    let upstream = upstream_name(name);
    let pool = name.replace('-', "_");
    format!(
        r#"upstream {upstream} {{
    server unix:/run/php/php{php_version}-fpm-{pool}.sock;
}}

server {{
    listen 80;
    listen [::]:80;
    server_name {domain};
    return 301 https://$server_name$request_uri;
}}

server {{
    # `listen ... http2` (not `http2 on;`) — works on nginx 1.24 and newer
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name {domain};

    ssl_certificate {cert};
    ssl_certificate_key {key};
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_cache shared:SSL:10m;

    set $MAGE_ROOT {mage_root};

    access_log /var/log/nginx/{name}.access.log;
    error_log /var/log/nginx/{name}.error.log;

    include {mage_root}/nginx.conf.serverkit;
}}
"#
    )
}

#[cfg(test)]
mod tests {
    #[test]
    fn compose_renders() {
        let y = super::compose_yaml(
            "shop1",
            34010,
            "s3cret",
            false,
            false,
            &super::default_service_versions(),
        );
        assert!(y.contains("127.0.0.1:34010:3306"));
        assert!(y.contains("127.0.0.1:34011:9200"));
        assert!(y.contains("container_name: magento-shop1-redis"));
        assert!(!y.contains("rabbitmq"));
        assert!(!y.contains("varnish"));
    }

    #[test]
    fn compose_with_rabbitmq() {
        let y = super::compose_yaml(
            "shop2",
            34020,
            "pw",
            true,
            false,
            &super::default_service_versions(),
        );
        assert!(y.contains("container_name: magento-shop2-rabbitmq"));
        assert!(y.contains("127.0.0.1:34023:5672"));
        assert!(y.contains("volumes:")); // volumes section survives the splice
    }

    #[test]
    fn compose_with_varnish() {
        let y = super::compose_yaml(
            "shop3",
            34030,
            "pw",
            false,
            true,
            &super::default_service_versions(),
        );
        assert!(y.contains("container_name: magento-shop3-varnish"));
        assert!(y.contains("127.0.0.1:34036:80"));
        assert!(y.contains("host.docker.internal:host-gateway"));
    }

    #[test]
    fn varnish_vhost_renders() {
        let v = super::magento_vhost_varnish(
            "shop3",
            "shop3.test",
            "/var/www/m/shop3/src",
            "8.3",
            34036,
            34037,
            None,
        );
        assert!(v.contains("proxy_pass http://127.0.0.1:34036;"));
        assert!(v.contains("listen 172.17.0.1:34037;"));
        assert!(v.contains("upstream fastcgi_backend_shop3"));
        let vcl = super::bootstrap_vcl(34037);
        assert!(vcl.contains(".port = \"34037\";"));
    }

    #[test]
    fn ssl_vhost_renders() {
        let v = super::magento_vhost_ssl(
            "s",
            "s.test",
            "/var/www/s",
            "8.3",
            "/etc/ssl/s.crt",
            "/etc/ssl/s.key",
        );
        assert!(v.contains("listen 443 ssl"));
        assert!(v.contains("return 301 https://"));
        assert!(v.contains("ssl_certificate /etc/ssl/s.crt;"));
    }

    #[test]
    fn vhost_renders() {
        let v = super::magento_vhost("shop1", "shop1.test", "/var/www/magento/shop1", "8.3");
        assert!(v.contains("upstream fastcgi_backend_shop1"));
        assert!(v.contains("unix:/run/php/php8.3-fpm-shop1.sock"));
        assert!(v.contains("set $MAGE_ROOT /var/www/magento/shop1;"));
        assert!(v.contains("include /var/www/magento/shop1/nginx.conf.serverkit;"));
    }

    #[test]
    fn upstream_names_unique_and_valid() {
        assert_eq!(super::upstream_name("my-store"), "fastcgi_backend_my_store");
    }

    #[test]
    fn headless_shared_vhost() {
        let v = super::magento_vhost_headless_shared(
            "shop2",
            "shop2.test",
            "/var/www/magento/shop2/src",
            "8.3",
            34027,
            "/admin_abc",
            3000,
            None,
            &["/checkout".to_string()],
            None,
        );
        assert!(v.contains("listen 127.0.0.1:34027;"));
        assert!(v.contains("~* ^/(admin_abc|rest|graphql|static|media|setup)(/|$)"));
        assert!(v.contains("location ^~ /checkout"));
        assert!(v.contains("proxy_pass http://127.0.0.1:3000;"));
    }

    #[test]
    fn headless_split_vhost() {
        let v = super::magento_vhost_headless_split(
            "shop2",
            "api.shop2.test",
            "admin.shop2.test",
            "/var/www/magento/shop2/src",
            "8.3",
            34027,
            "/admin_abc",
            "api_only",
            None,
        );
        assert!(v.contains("server_name api.shop2.test admin.shop2.test;"));
        assert!(v.contains("~* ^/(rest|graphql|static|media)(/|$)"));
        assert!(v.contains("~* ^/(admin_abc|static|media|setup)(/|$)"));
        assert!(v.contains("return 302 /admin_abc;"));
        // api server must NOT route the admin path
        let api_server = v.split("# Admin domain").next().unwrap();
        assert!(!api_server
            .split("# API domain")
            .nth(1)
            .unwrap()
            .contains("admin_abc"));
    }

    #[test]
    fn frontend_unit_renders() {
        let u = super::frontend_unit(
            "shop2",
            "/var/www/fe",
            "/usr/bin/node server.js",
            3456,
            "ubuntu",
        );
        assert!(u.contains("User=ubuntu"));
        assert!(u.contains("WorkingDirectory=/var/www/fe"));
        assert!(u.contains("Environment=PORT=3456"));
        assert!(u.contains("ExecStart=/usr/bin/node server.js"));
        assert!(u.contains("Restart=always"));
    }

    #[test]
    fn headless_static_frontend() {
        let v = super::frontend_vhost("shop2", "store.test", 0, Some("/var/www/fe/out"), None);
        assert!(v.contains("root /var/www/fe/out;"));
        assert!(v.contains("try_files $uri $uri/ /index.html;"));
        assert!(!v.contains("proxy_pass"));
        let s = super::frontend_vhost(
            "shop2",
            "store.test",
            3000,
            None,
            Some(("/c.crt", "/c.key")),
        );
        assert!(s.contains("listen 443 ssl http2;"));
        assert!(s.contains("return 301 https://"));
    }
}
