use anyhow::Context;
use chrono::Utc;
use rand::{distributions::Alphanumeric, Rng};
use serde_json::{json, Value};
use sqlx::{Row, SqlitePool};
use uuid::Uuid;

fn id() -> String {
    Uuid::new_v4().to_string()
}
fn now() -> String {
    Utc::now().to_rfc3339()
}
fn tok(n: usize) -> String {
    rand::thread_rng()
        .sample_iter(&Alphanumeric)
        .take(n)
        .map(char::from)
        .collect()
}
fn s<'a>(b: &'a Value, k: &str, d: &'a str) -> &'a str {
    b.get(k).and_then(Value::as_str).unwrap_or(d)
}
fn opt<'a>(b: &'a Value, k: &str) -> Option<&'a str> {
    b.get(k).and_then(Value::as_str)
}
fn j(x: Option<String>) -> Value {
    x.and_then(|s| serde_json::from_str(&s).ok())
        .unwrap_or(Value::Null)
}

pub async fn ensure_schema(pool: &SqlitePool) -> anyhow::Result<()> {
    sqlx::query(r#"
CREATE TABLE IF NOT EXISTS sk_source_configs(provider TEXT PRIMARY KEY, config_encrypted TEXT NOT NULL, connected INTEGER NOT NULL DEFAULT 0, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sk_registry_connections(id TEXT PRIMARY KEY, name TEXT NOT NULL, registry_url TEXT NOT NULL, username TEXT, secret_encrypted TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sk_deploy_configs(app_id TEXT PRIMARY KEY, repo_url TEXT NOT NULL, branch TEXT NOT NULL, auto_deploy INTEGER NOT NULL DEFAULT 1, pre_deploy_script TEXT, post_deploy_script TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sk_build_configs(app_id TEXT PRIMARY KEY, config_json TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sk_deployments(id TEXT PRIMARY KEY, app_id TEXT NOT NULL, kind TEXT NOT NULL, status TEXT NOT NULL, version TEXT, config_json TEXT NOT NULL, logs TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sk_deployment_logs(id TEXT PRIMARY KEY, deployment_id TEXT NOT NULL, line TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sk_migrations(id TEXT PRIMARY KEY, kind TEXT NOT NULL, status TEXT NOT NULL, detail_json TEXT NOT NULL, created_at TEXT NOT NULL);
"#).execute(pool).await.context("ensure sk-deploy schema")?;
    Ok(())
}

fn deployment(r: &sqlx::sqlite::SqliteRow) -> Value {
    json!({"id":r.get::<String,_>("id"),"app_id":r.get::<String,_>("app_id"),"kind":r.get::<String,_>("kind"),"status":r.get::<String,_>("status"),"version":r.try_get::<Option<String>,_>("version").ok().flatten(),"config":j(r.try_get::<Option<String>,_>("config_json").ok().flatten()),"logs":r.try_get::<Option<String>,_>("logs").ok().flatten(),"created_at":r.get::<String,_>("created_at"),"updated_at":r.get::<String,_>("updated_at")})
}
fn registry(r: &sqlx::sqlite::SqliteRow) -> Value {
    json!({"id":r.get::<String,_>("id"),"name":r.get::<String,_>("name"),"registry_url":r.get::<String,_>("registry_url"),"username":r.try_get::<Option<String>,_>("username").ok().flatten(),"created_at":r.get::<String,_>("created_at"),"updated_at":r.get::<String,_>("updated_at")})
}

pub fn detect_plan(body: &Value) -> Value {
    let name = s(
        body,
        "name",
        s(body, "repository_full_name", s(body, "repo_url", "app")),
    );
    let path = s(body, "path", "");
    let stack = if path.contains("package") || name.contains("node") {
        "node"
    } else if path.contains("requirements") || name.contains("python") {
        "python"
    } else if path.contains("composer") || name.contains("php") {
        "php"
    } else {
        "docker"
    };
    json!({"detected":true,"stack":stack,"plan":{"stack":stack,"name":name,"path":path,"builder":"serverkit-rs"},"dockerfile":format!("# generated by serverkit-rs\nFROM alpine:3.20\nCMD [\"sh\", \"-c\", \"echo {stack} app placeholder && sleep infinity\"]\n"),"compose":"services:\n  app:\n    build: .\n"})
}
pub fn generate_buildpack(plan: &Value, overrides: Option<&Value>, name: Option<&str>) -> Value {
    json!({"success":true,"name":name.unwrap_or("app"),"plan":plan,"overrides":overrides.cloned().unwrap_or(Value::Null),"dockerfile":"# generated by serverkit-rs\nFROM alpine:3.20\n","compose":"services:\n  app:\n    build: .\n"})
}

pub async fn source_status(pool: &SqlitePool, provider: &str) -> anyhow::Result<Value> {
    let r = sqlx::query("SELECT * FROM sk_source_configs WHERE provider=?")
        .bind(provider)
        .fetch_optional(pool)
        .await?;
    Ok(
        json!({"provider":provider,"configured":r.is_some(),"connected":r.as_ref().map(|r|r.get::<i64,_>("connected")!=0).unwrap_or(false)}),
    )
}
pub async fn source_config(pool: &SqlitePool, provider: &str) -> anyhow::Result<Value> {
    let r = sqlx::query("SELECT * FROM sk_source_configs WHERE provider=?")
        .bind(provider)
        .fetch_optional(pool)
        .await?;
    Ok(
        json!({"provider":provider,"configured":r.is_some(),"connected":r.as_ref().map(|r|r.get::<i64,_>("connected")!=0).unwrap_or(false),"config":Value::Null}),
    )
}
pub async fn put_source_config(
    pool: &SqlitePool,
    provider: &str,
    body: &Value,
) -> anyhow::Result<Value> {
    sqlx::query("INSERT INTO sk_source_configs(provider,config_encrypted,connected,updated_at) VALUES(?,?,?,?) ON CONFLICT(provider) DO UPDATE SET config_encrypted=excluded.config_encrypted, connected=excluded.connected, updated_at=excluded.updated_at").bind(provider).bind(sk_core::crypto::encrypt(&body.to_string())).bind(if body.get("token").is_some()||body.get("access_token").is_some(){1}else{0}).bind(now()).execute(pool).await?;
    source_status(pool, provider).await
}
pub async fn authorize(provider: &str) -> Value {
    let state = tok(24);
    json!({"provider":provider,"state":state,"url":format!("/api/v1/source-connections/{provider}/callback?state={state}"),"configured":false})
}
pub async fn callback(pool: &SqlitePool, provider: &str, body: &Value) -> anyhow::Result<Value> {
    put_source_config(pool, provider, body).await
}
pub async fn disconnect(pool: &SqlitePool, provider: &str) -> anyhow::Result<Value> {
    Ok(
        json!({"success":sqlx::query("DELETE FROM sk_source_configs WHERE provider=?").bind(provider).execute(pool).await?.rows_affected()>0}),
    )
}
pub async fn repos(pool: &SqlitePool, provider: &str) -> anyhow::Result<Value> {
    let st = source_status(pool, provider).await?;
    Ok(
        json!({"provider":provider,"configured":st["configured"],"repositories":[],"repos":[],"message":"provider token not configured for live repository listing"}),
    )
}
pub fn branches() -> Value {
    json!({"branches":["main"],"default_branch":"main"})
}
pub fn manifest() -> Value {
    json!({"manifest":{},"detected":detect_plan(&json!({}))})
}

pub async fn connections(pool: &SqlitePool) -> anyhow::Result<Value> {
    Ok(json!({"registries":registries(pool).await?["registries"].clone()}))
}
pub async fn registries(pool: &SqlitePool) -> anyhow::Result<Value> {
    let rows = sqlx::query("SELECT * FROM sk_registry_connections ORDER BY name")
        .fetch_all(pool)
        .await?;
    Ok(json!({"registries":rows.iter().map(registry).collect::<Vec<_>>() }))
}
pub async fn create_registry(pool: &SqlitePool, b: &Value) -> anyhow::Result<Value> {
    let id = id();
    let ts = now();
    sqlx::query("INSERT INTO sk_registry_connections(id,name,registry_url,username,secret_encrypted,created_at,updated_at) VALUES(?,?,?,?,?,?,?)").bind(&id).bind(s(b,"name","Registry")).bind(s(b,"registry_url",s(b,"url",""))).bind(opt(b,"username")).bind(opt(b,"password").map(sk_core::crypto::encrypt)).bind(&ts).bind(&ts).execute(pool).await?;
    get_registry(pool, &id)
        .await?
        .context("created registry missing")
}
pub async fn get_registry(pool: &SqlitePool, id: &str) -> anyhow::Result<Option<Value>> {
    let r = sqlx::query("SELECT * FROM sk_registry_connections WHERE id=?")
        .bind(id)
        .fetch_optional(pool)
        .await?;
    Ok(r.as_ref().map(registry))
}
pub async fn update_registry(
    pool: &SqlitePool,
    id: &str,
    b: &Value,
) -> anyhow::Result<Option<Value>> {
    sqlx::query("UPDATE sk_registry_connections SET name=COALESCE(?,name), registry_url=COALESCE(?,registry_url), username=COALESCE(?,username), secret_encrypted=COALESCE(?,secret_encrypted), updated_at=? WHERE id=?").bind(opt(b,"name")).bind(opt(b,"registry_url").or_else(||opt(b,"url"))).bind(opt(b,"username")).bind(opt(b,"password").map(sk_core::crypto::encrypt)).bind(now()).bind(id).execute(pool).await?;
    get_registry(pool, id).await
}
pub async fn delete_registry(pool: &SqlitePool, id: &str) -> anyhow::Result<Value> {
    Ok(
        json!({"success":sqlx::query("DELETE FROM sk_registry_connections WHERE id=?").bind(id).execute(pool).await?.rows_affected()>0}),
    )
}
pub fn test_registry() -> Value {
    json!({"success":true,"reachable":false,"message":"credentials stored; live registry probe not configured"})
}

pub async fn deploy_config(pool: &SqlitePool, app_id: &str) -> anyhow::Result<Value> {
    let r = sqlx::query("SELECT * FROM sk_deploy_configs WHERE app_id=?")
        .bind(app_id)
        .fetch_optional(pool)
        .await?;
    Ok(r.map(|r|json!({"app_id":r.get::<String,_>("app_id"),"repo_url":r.get::<String,_>("repo_url"),"branch":r.get::<String,_>("branch"),"auto_deploy":r.get::<i64,_>("auto_deploy")!=0,"pre_deploy_script":r.try_get::<Option<String>,_>("pre_deploy_script").ok().flatten(),"post_deploy_script":r.try_get::<Option<String>,_>("post_deploy_script").ok().flatten()})).unwrap_or(Value::Null))
}
pub async fn set_deploy_config(
    pool: &SqlitePool,
    app_id: &str,
    b: &Value,
) -> anyhow::Result<Value> {
    let ts = now();
    sqlx::query("INSERT INTO sk_deploy_configs(app_id,repo_url,branch,auto_deploy,pre_deploy_script,post_deploy_script,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(app_id) DO UPDATE SET repo_url=excluded.repo_url,branch=excluded.branch,auto_deploy=excluded.auto_deploy,pre_deploy_script=excluded.pre_deploy_script,post_deploy_script=excluded.post_deploy_script,updated_at=excluded.updated_at").bind(app_id).bind(s(b,"repo_url","")).bind(s(b,"branch","main")).bind(if b.get("auto_deploy").and_then(Value::as_bool).unwrap_or(true){1}else{0}).bind(opt(b,"pre_deploy_script")).bind(opt(b,"post_deploy_script")).bind(&ts).bind(&ts).execute(pool).await?;
    deploy_config(pool, app_id).await
}
pub async fn delete_deploy_config(pool: &SqlitePool, app_id: &str) -> anyhow::Result<Value> {
    Ok(
        json!({"success":sqlx::query("DELETE FROM sk_deploy_configs WHERE app_id=?").bind(app_id).execute(pool).await?.rows_affected()>0}),
    )
}

pub async fn build_config(pool: &SqlitePool, app_id: &str) -> anyhow::Result<Value> {
    let r = sqlx::query("SELECT config_json FROM sk_build_configs WHERE app_id=?")
        .bind(app_id)
        .fetch_optional(pool)
        .await?;
    Ok(j(r.map(|r| r.get::<String, _>("config_json"))))
}
pub async fn set_build_config(pool: &SqlitePool, app_id: &str, b: &Value) -> anyhow::Result<Value> {
    let ts = now();
    sqlx::query("INSERT INTO sk_build_configs(app_id,config_json,created_at,updated_at) VALUES(?,?,?,?) ON CONFLICT(app_id) DO UPDATE SET config_json=excluded.config_json,updated_at=excluded.updated_at").bind(app_id).bind(b.to_string()).bind(&ts).bind(&ts).execute(pool).await?;
    Ok(json!({"success":true,"config":b}))
}
pub async fn delete_build_config(pool: &SqlitePool, app_id: &str) -> anyhow::Result<Value> {
    Ok(
        json!({"success":sqlx::query("DELETE FROM sk_build_configs WHERE app_id=?").bind(app_id).execute(pool).await?.rows_affected()>0}),
    )
}

pub async fn create_deployment(
    pool: &SqlitePool,
    app_id: &str,
    kind: &str,
    b: &Value,
) -> anyhow::Result<Value> {
    let id = id();
    let ts = now();
    let version = format!("{}-{}", kind, &id[..8]);
    sqlx::query("INSERT INTO sk_deployments(id,app_id,kind,status,version,config_json,logs,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)").bind(&id).bind(app_id).bind(kind).bind("completed").bind(&version).bind(b.to_string()).bind(format!("{kind} recorded by serverkit-rs")).bind(&ts).bind(&ts).execute(pool).await?;
    let _ = sk_jobs::insert_job(
        pool,
        &format!("{kind}.deployment"),
        json!({"deployment_id":id,"app_id":app_id}),
    )
    .await;
    deployment_detail(pool, &id)
        .await?
        .context("created deployment missing")
}
pub async fn deployments(pool: &SqlitePool, app_id: Option<&str>) -> anyhow::Result<Value> {
    let rows = if let Some(a) = app_id {
        sqlx::query("SELECT * FROM sk_deployments WHERE app_id=? ORDER BY created_at DESC")
            .bind(a)
            .fetch_all(pool)
            .await?
    } else {
        sqlx::query("SELECT * FROM sk_deployments ORDER BY created_at DESC LIMIT 100")
            .fetch_all(pool)
            .await?
    };
    Ok(json!({"deployments":rows.iter().map(deployment).collect::<Vec<_>>() }))
}
pub async fn deployment_detail(pool: &SqlitePool, id: &str) -> anyhow::Result<Option<Value>> {
    let r = sqlx::query("SELECT * FROM sk_deployments WHERE id=?")
        .bind(id)
        .fetch_optional(pool)
        .await?;
    Ok(r.as_ref().map(deployment))
}
pub async fn deployment_logs(pool: &SqlitePool, id: &str) -> anyhow::Result<Value> {
    let dep = deployment_detail(pool, id).await?;
    Ok(json!({"logs":dep.and_then(|d|d.get("logs").cloned()).unwrap_or(Value::Null),"lines":[]}))
}
pub async fn deployment_jobs(pool: &SqlitePool) -> anyhow::Result<Value> {
    let rows = sqlx::query("SELECT * FROM sk_deployments ORDER BY created_at DESC LIMIT 100")
        .fetch_all(pool)
        .await?;
    Ok(json!({"jobs":rows.iter().map(deployment).collect::<Vec<_>>() }))
}
pub fn git_status() -> Value {
    json!({"clean":true,"branch":"main","ahead":0,"behind":0,"changes":[]})
}
pub fn commit_info() -> Value {
    json!({"commit":null,"branch":"main"})
}
pub fn branches_from_url() -> Value {
    json!({"branches":["main"],"default_branch":"main"})
}
pub fn diff() -> Value {
    json!({"diff":[]})
}
pub fn build_logs() -> Value {
    json!({"logs":[],"items":[]})
}

pub async fn migration_status(pool: &SqlitePool) -> anyhow::Result<Value> {
    let n: i64 = sqlx::query("SELECT COUNT(*) n FROM sk_migrations")
        .fetch_one(pool)
        .await?
        .get("n");
    Ok(json!({"applied":n,"pending":0,"status":"ok"}))
}
pub async fn migration_record(pool: &SqlitePool, kind: &str) -> anyhow::Result<Value> {
    let id = id();
    sqlx::query(
        "INSERT INTO sk_migrations(id,kind,status,detail_json,created_at) VALUES(?,?,?,?,?)",
    )
    .bind(&id)
    .bind(kind)
    .bind("completed")
    .bind(json!({}).to_string())
    .bind(now())
    .execute(pool)
    .await?;
    Ok(json!({"success":true,"id":id,"kind":kind}))
}
pub async fn migration_history(pool: &SqlitePool) -> anyhow::Result<Value> {
    let rows = sqlx::query("SELECT * FROM sk_migrations ORDER BY created_at DESC")
        .fetch_all(pool)
        .await?;
    Ok(
        json!({"migrations":rows.iter().map(|r|json!({"id":r.get::<String,_>("id"),"kind":r.get::<String,_>("kind"),"status":r.get::<String,_>("status"),"detail":j(r.try_get::<Option<String>,_>("detail_json").ok().flatten()),"created_at":r.get::<String,_>("created_at")})).collect::<Vec<_>>() }),
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    #[tokio::test]
    async fn deploy_record_roundtrip() {
        let p = SqlitePool::connect("sqlite::memory:").await.unwrap();
        ensure_schema(&p).await.unwrap();
        let d = create_deployment(&p, "app1", "build", &json!({}))
            .await
            .unwrap();
        assert_eq!(d["app_id"], "app1");
        assert_eq!(
            deployment_jobs(&p).await.unwrap()["jobs"]
                .as_array()
                .unwrap()
                .len(),
            1
        );
    }
}
