"""Per-site brute-force jail management on top of the reverse-proxy/log layer.

ServerKit's read-only Fail2ban integration (``SecurityService``) can list and
ban/unban, but it cannot *create* jails. This service is the write half: it
generates ServerKit-owned Fail2ban filter + per-site jail configs that watch a
managed site's nginx access log and ban IPs that hammer the WordPress login.

This is what redeems the ``WpSecurityService`` deferral: a managed WordPress site
already gets a per-site nginx vhost whose access log
(``NginxService.site_access_log_path``) records ``POST /wp-login.php`` /
``POST /xmlrpc.php`` with the *real* client IP (nginx is the edge listener, so the
log's remote address is the client, not a proxy). A jail pointed at that log is
therefore a real per-site brute-force jail.

Design:
* **Ownership-guarded** — only ever writes/reads/removes files named
  ``serverkit-*`` under ``filter.d/`` and ``jail.d/``; an operator's own jails are
  never touched. The per-site jail filename is sanitised to ``[a-z0-9_-]`` so it
  can never escape the jail directory.
* **Best-effort, never raises; Linux-only** — on Windows (dev) or when Fail2ban
  is absent, every mutating call returns a ``skipped`` descriptor instead of
  failing, so site creation degrades gracefully and the UI can surface "fail2ban
  not available".
* **Config files are the source of truth** — a site is protected iff its
  ``jail.d/serverkit-<key>.conf`` exists (same model nginx sites use); there is no
  parallel DB state to drift.
"""
import os
import re
import logging

from app.utils.system import run_privileged, is_command_available, ServiceControl
from app.services.nginx_service import NginxService

logger = logging.getLogger(__name__)


class Fail2banJailService:
    FILTER_DIR = '/etc/fail2ban/filter.d'
    JAIL_DIR = '/etc/fail2ban/jail.d'

    # ServerKit-owned filter name (filter.d/serverkit-wp-login.conf).
    WP_FILTER = 'serverkit-wp-login'
    # Every ServerKit jail file + jail name carries this prefix — both the
    # ownership marker and the namespace that keeps us off operator jails.
    JAIL_PREFIX = 'serverkit-'

    # Default thresholds: 5 login POSTs within 10 min -> 1 hour ban.
    MAXRETRY = 5
    FINDTIME = 600
    BANTIME = 3600

    # WordPress login / XML-RPC brute-force filter. Raw string: the regex needs a
    # literal backslash-dot. <HOST> is Fail2ban's IP capture; for the nginx
    # combined log line "<ip> - - [time] \"POST /wp-login.php ...\"" it captures the
    # real client IP. Date is auto-detected by Fail2ban for the common log format.
    FILTER_CONTENT = r'''# ServerKit-managed Fail2ban filter: WordPress login / XML-RPC brute force.
# Matches POSTs to wp-login.php and xmlrpc.php in the nginx combined access log.
# nginx is the edge listener, so <HOST> (the log's remote address) is the real
# client IP. Generated by Fail2banJailService - do not edit by hand (regenerated).
[Definition]
failregex = ^<HOST> -.*"POST /wp-login\.php
            ^<HOST> -.*"POST /xmlrpc\.php
ignoreregex =
'''

    JAIL_TEMPLATE = '''# ServerKit-managed brute-force jail for site "{site}".
# Generated by Fail2banJailService - do not edit by hand (regenerated on change).
[{jail}]
enabled = true
filter = {filter}
logpath = {logpath}
port = http,https
maxretry = {maxretry}
findtime = {findtime}
bantime = {bantime}
'''

    # ---------- availability ----------

    @classmethod
    def available(cls):
        """True only on a Linux host where the fail2ban client is installed."""
        if os.name == 'nt':
            return False
        return is_command_available('fail2ban-client')

    @staticmethod
    def _unavailable():
        return {
            'success': True, 'skipped': True, 'available': False, 'reason': 'unavailable',
            'message': 'fail2ban is not available on this host; brute-force protection is inactive.',
        }

    # ---------- naming (pure, filesystem-free) ----------

    @staticmethod
    def _sanitize(name):
        """Reduce a site name to a Fail2ban/filename-safe key (``[a-z0-9_-]``).

        Strips everything else — so path separators and dots can't survive — which
        is what makes the derived jail filename traversal-proof."""
        return re.sub(r'[^a-zA-Z0-9_-]', '-', (name or '')).strip('-') or 'site'

    @classmethod
    def jail_name(cls, app):
        """``serverkit-<key>`` jail name for an application."""
        return cls.JAIL_PREFIX + cls._sanitize(getattr(app, 'name', None))

    @classmethod
    def _jail_filename(cls, app):
        return f'{cls.jail_name(app)}.conf'

    @classmethod
    def _jail_path(cls, app):
        """Absolute path of the per-site jail file, guarded so it can only ever be
        a ServerKit-owned file inside JAIL_DIR."""
        filename = cls._jail_filename(app)
        if (not filename.startswith(cls.JAIL_PREFIX)
                or '/' in filename or '\\' in filename or '..' in filename):
            # Unreachable given _sanitize, but refuse rather than risk a stray path.
            raise ValueError(f'refusing to target non-ServerKit jail file: {filename!r}')
        return os.path.join(cls.JAIL_DIR, filename)

    # ---------- file helpers ----------

    @staticmethod
    def _read_text(path):
        try:
            with open(path, 'r') as fh:
                return fh.read()
        except Exception:
            return None

    @staticmethod
    def _write_file(path, content):
        """Write *content* to *path* with privilege (sudo tee), like NginxService."""
        try:
            proc = run_privileged(['tee', path], input=content)
            if proc.returncode != 0:
                return {'success': False, 'error': (proc.stderr or 'write failed').strip()}
            return {'success': True, 'path': path}
        except Exception as e:
            return {'success': False, 'error': str(e)}

    @staticmethod
    def _ensure_logpath(logpath):
        """Make sure the access log exists before the jail references it — a jail
        whose logpath is missing fails to start. nginx creates the file on reload;
        this is belt-and-suspenders for the race where the site has had no hits."""
        try:
            run_privileged(['touch', logpath])
        except Exception:
            pass

    # ---------- filter ----------

    @classmethod
    def ensure_filter(cls):
        """Write the ServerKit WP-login filter if missing or out of date."""
        if not cls.available():
            return cls._unavailable()
        path = os.path.join(cls.FILTER_DIR, f'{cls.WP_FILTER}.conf')
        existing = cls._read_text(path)
        if existing is not None and existing.strip() == cls.FILTER_CONTENT.strip():
            return {'success': True, 'path': path, 'changed': False}
        res = cls._write_file(path, cls.FILTER_CONTENT)
        if not res.get('success'):
            return res
        return {'success': True, 'path': path, 'changed': True}

    # ---------- jail lifecycle ----------

    @classmethod
    def _render_jail(cls, app, logpath, maxretry, findtime, bantime):
        return cls.JAIL_TEMPLATE.format(
            jail=cls.jail_name(app), site=getattr(app, 'name', ''), filter=cls.WP_FILTER,
            logpath=logpath,
            maxretry=maxretry or cls.MAXRETRY,
            findtime=findtime or cls.FINDTIME,
            bantime=bantime or cls.BANTIME,
        )

    @classmethod
    def enable_wp_jail(cls, app, *, maxretry=None, findtime=None, bantime=None):
        """Create/refresh a WP brute-force jail for *app* and reload fail2ban.

        Idempotent (regenerates the jail file). Best-effort: returns a ``skipped``
        descriptor when fail2ban is unavailable rather than raising, so callers in
        the site-create path never fail because of it."""
        if not cls.available():
            return cls._unavailable()
        if not getattr(app, 'name', None):
            return {'success': False, 'error': 'application has no name'}

        flt = cls.ensure_filter()
        if not flt.get('success'):
            return flt

        logpath = NginxService.site_access_log_path(app.name)
        cls._ensure_logpath(logpath)

        try:
            jail_path = cls._jail_path(app)
        except ValueError as e:
            return {'success': False, 'error': str(e)}

        written = cls._write_file(jail_path, cls._render_jail(
            app, logpath, maxretry, findtime, bantime))
        if not written.get('success'):
            return written

        reloaded = cls.reload()
        return {
            'success': True, 'enabled': True, 'jail': cls.jail_name(app),
            'path': jail_path, 'logpath': logpath,
            'reloaded': reloaded.get('success'), 'reload_message': reloaded.get('message'),
        }

    @classmethod
    def disable_jail(cls, app):
        """Remove a site's ServerKit jail file and reload fail2ban. No-op (success)
        when the jail does not exist or fail2ban is unavailable."""
        if not cls.available():
            return cls._unavailable()
        try:
            jail_path = cls._jail_path(app)
        except ValueError as e:
            return {'success': False, 'error': str(e)}

        if not os.path.exists(jail_path):
            return {'success': True, 'removed': False, 'message': 'no jail to remove'}
        try:
            proc = run_privileged(['rm', '-f', jail_path])
            if proc.returncode != 0:
                return {'success': False, 'error': (proc.stderr or 'remove failed').strip()}
        except Exception as e:
            return {'success': False, 'error': str(e)}

        reloaded = cls.reload()
        return {'success': True, 'removed': True, 'jail': cls.jail_name(app),
                'reloaded': reloaded.get('success')}

    @classmethod
    def reload(cls):
        """``fail2ban-client reload`` (keeps existing bans), falling back to a
        service restart if the client call fails."""
        if not cls.available():
            return cls._unavailable()
        try:
            proc = run_privileged(['fail2ban-client', 'reload'], timeout=30)
            if proc.returncode == 0:
                return {'success': True, 'message': 'fail2ban reloaded'}
        except Exception:
            pass
        try:
            res = ServiceControl.restart('fail2ban', timeout=30)
            return {'success': res.returncode == 0,
                    'message': 'fail2ban restarted' if res.returncode == 0
                    else (res.stderr or 'reload failed')}
        except Exception as e:
            return {'success': False, 'error': str(e)}

    # ---------- status / actions ----------

    @classmethod
    def get_status(cls, app):
        """Per-site brute-force status: availability, whether the jail exists, the
        active thresholds, and (when fail2ban is running) live ban counts."""
        info = {
            'available': cls.available(),
            'enabled': False,
            'jail': cls.jail_name(app),
            'thresholds': {'maxretry': cls.MAXRETRY, 'findtime': cls.FINDTIME,
                           'bantime': cls.BANTIME},
            'fail2ban_installed': False,
            'fail2ban_running': False,
            'currently_banned': 0,
            'total_banned': 0,
            'currently_failed': 0,
            'banned_ips': [],
        }
        if not cls.available():
            return info

        try:
            info['enabled'] = os.path.exists(cls._jail_path(app))
        except ValueError:
            info['enabled'] = False

        from app.services.security_service import SecurityService
        f2b = SecurityService.get_fail2ban_status()
        info['fail2ban_installed'] = bool(f2b.get('installed'))
        info['fail2ban_running'] = bool(f2b.get('service_running'))

        if info['enabled'] and info['fail2ban_running']:
            js = SecurityService.get_fail2ban_jail_status(info['jail'])
            if js.get('success'):
                info.update({
                    'currently_banned': js.get('currently_banned', 0),
                    'total_banned': js.get('total_banned', 0),
                    'currently_failed': js.get('currently_failed', 0),
                    'banned_ips': js.get('banned_ips', []),
                })
        return info

    @classmethod
    def unban(cls, app, ip):
        """Unban *ip* from this site's jail (thin wrapper over SecurityService)."""
        if not cls.available():
            return cls._unavailable()
        from app.services.security_service import SecurityService
        return SecurityService.unban_ip(ip, cls.jail_name(app))
