#!/usr/bin/env python3
"""Validate and generate the serverkit-rs API route ledger.

This is the Phase 0 no-fallback gate. It does not claim every route is already
implemented; it guarantees every frontend-referenced route is explicitly owned
and classified. Unknown, stub, and compat-empty classifications fail.
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from dataclasses import asdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from audit_frontend_routes import RouteUse, extract_routes  # noqa: E402

ALLOWED_STATUSES = {"implemented", "planned", "removed-from-frontend"}
FORBIDDEN_STATUSES = {"stub", "compat-empty", "unknown"}
LEDGER_PATH = Path("docs/API_ROUTE_LEDGER.md")
FAMILY_PATH = Path("docs/api_route_families.json")


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def load_families(root: Path) -> dict:
    path = root / FAMILY_PATH
    with path.open() as f:
        return json.load(f)


def unique_routes(routes: list[RouteUse]) -> dict[tuple[str, str], RouteUse]:
    merged: dict[tuple[str, str], RouteUse] = {}
    sources: dict[tuple[str, str], list[str]] = defaultdict(list)
    for r in routes:
        key = (r.method, r.path)
        if key not in merged:
            merged[key] = r
        sources[key].append(r.source)
    out = {}
    for key, r in merged.items():
        out[key] = RouteUse(r.method, r.path, r.family, ", ".join(sorted(set(sources[key]))))
    return out


def validate(routes: list[RouteUse], families: dict) -> list[str]:
    errors: list[str] = []
    used_families = sorted({r.family for r in routes})
    for family in used_families:
        meta = families.get(family)
        if not meta:
            errors.append(f"unknown route family: {family}")
            continue
        status = meta.get("status", "unknown")
        if status in FORBIDDEN_STATUSES or status not in ALLOWED_STATUSES:
            errors.append(f"invalid status for family {family}: {status!r}")
        if status == "implemented":
            owner = str(meta.get("owner", ""))
            if "stubs" in owner or "compat-empty" in owner or "routes::compat" in owner:
                errors.append(f"family {family} is marked implemented but owner looks fallback-like: {owner}")
    unused = sorted(set(families) - set(used_families))
    for family in unused:
        meta = families[family]
        if meta.get("status") == "implemented":
            errors.append(f"family {family} is marked implemented but no frontend route currently references it")
    return errors


def ledger_markdown(routes: list[RouteUse], families: dict) -> str:
    uniq = unique_routes(routes)
    rows = sorted(uniq.values(), key=lambda r: (r.family, r.path, r.method))
    counts: dict[str, int] = defaultdict(int)
    for r in rows:
        counts[r.family] += 1

    lines: list[str] = []
    lines.append("# API Route Ledger")
    lines.append("")
    lines.append("Generated by `scripts/check_route_ledger.py --write-ledger`.")
    lines.append("")
    lines.append("> Status values are intentional: `planned` means the route is owned by a Rust subsystem roadmap item, not that a stub is acceptable. `implemented` must not point to `routes/stubs.rs` or empty compatibility handlers.")
    lines.append("")
    lines.append("## Summary by family")
    lines.append("")
    lines.append("| Family | Routes | Status | Phase | Owner | Note |")
    lines.append("|---|---:|---|---:|---|---|")
    for family in sorted(counts):
        meta = families.get(family, {})
        lines.append(
            f"| `{family}` | {counts[family]} | {meta.get('status', 'unknown')} | {meta.get('phase', '')} | {meta.get('owner', '')} | {meta.get('note', '')} |"
        )
    lines.append("")
    lines.append("## Route ledger")
    lines.append("")
    lines.append("| Method | Path | Family | Status | Phase | Owner | Frontend source |")
    lines.append("|---|---|---|---|---:|---|---|")
    for r in rows:
        meta = families.get(r.family, {})
        lines.append(
            f"| `{r.method}` | `{r.path}` | `{r.family}` | {meta.get('status', 'unknown')} | {meta.get('phase', '')} | {meta.get('owner', '')} | `{r.source}` |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write-ledger", action="store_true", help="rewrite docs/API_ROUTE_LEDGER.md")
    parser.add_argument("--check-ledger", action="store_true", help="fail if docs/API_ROUTE_LEDGER.md is stale")
    parser.add_argument("--json", action="store_true", help="print normalized inventory JSON")
    args = parser.parse_args()

    root = repo_root()
    routes = extract_routes(root)
    families = load_families(root)
    errors = validate(routes, families)
    if errors:
        for err in errors:
            print(f"route-ledger error: {err}", file=sys.stderr)
        return 1

    if args.json:
        print(json.dumps([asdict(r) for r in routes], indent=2, sort_keys=True))

    generated = ledger_markdown(routes, families)
    ledger_file = root / LEDGER_PATH
    if args.write_ledger:
        ledger_file.write_text(generated)
        print(f"wrote {LEDGER_PATH}")
    if args.check_ledger:
        if not ledger_file.exists():
            print(f"route-ledger error: missing {LEDGER_PATH}; run scripts/check_route_ledger.py --write-ledger", file=sys.stderr)
            return 1
        current = ledger_file.read_text()
        if current != generated:
            print(f"route-ledger error: stale {LEDGER_PATH}; run scripts/check_route_ledger.py --write-ledger", file=sys.stderr)
            return 1

    uniq = unique_routes(routes)
    print(f"route-ledger ok: {len(uniq)} frontend routes across {len({r.family for r in uniq.values()})} families")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
